#!/usr/bin/env bash

. "$(dirname $0)/sb-load-util"

# 󰸈   |   \Uf0e08   |  VOLUME
# 󰖀   |   \Uf0580   |  VOLUME WITH ONE SOUND WAVE
#    |   \uf028    |  VOLUME WITH THREE SOUND WAVES

SPEAKER="\Uf0e08"
SPEAKER_WITH_ONE_WAVE="\Uf0580"
SPEAKER_WITH_THREE_WAVES="\uf028"

DEVICE="@DEFAULT_AUDIO_SINK@"

STEP=0.05

function decrease_volume() {
  wpctl set-volume $DEVICE --limit 1.0 $STEP-
  compute
}

function increase_volume() {
  wpctl set-mute $DEVICE 0
  wpctl set-volume $DEVICE --limit 1.0 $STEP+
  compute
}

function toggle_mute() {
  wpctl set-mute $DEVICE toggle
  compute
}

function switch_sink() {
  # TODO: Do I really need it?
  compute
}

function success() {
  refresh_block $SB_AUDIO "Volume changed"
  exit 0
}

function get_icon() {
  local volume=$1
  if [[ $volume -eq 0 ]]; then
    echo -e $SPEAKER
  elif [[ $volume -le 60 ]]; then
    echo -e $SPEAKER_WITH_ONE_WAVE
  else
    echo -e $SPEAKER_WITH_THREE_WAVES
  fi
}

function compute() {
  local volume=$(wpctl get-volume $DEVICE)   # Volume: 0.69 (or) Volume: 0.69 [MUTED]
  echo $volume | grep 'MUTED' > /dev/null
  local muted=$?

  if [[ $muted -eq 0 ]]; then
    volume=""
  else
    volume=$(echo $volume | cut -d' ' -f2)
    volume=$(echo "$volume * 100 / 1" | bc)
  fi

  local icon=$(get_icon $volume)
  display $icon $volume

  success
}

BLOCK_BUTTON=${1:-$BLOCK_BUTTON}

case $BLOCK_BUTTON in
    1) increase_volume ;;
    2) notify-send "Vera velaye illayada unaku?" && compute ;;
    3) decrease_volume ;;
    4) decrease_volume ;;
    5) increase_volume ;;
    8) toggle_mute ;;
esac

compute
